apiVersion: apps/v1
kind: Deployment
metadata:
        name: iot-app
        labels:
                app: iot-app
spec:
        selector:
                matchLabels:
                        app: iot-app
        replicas: 1
        template:
                metadata:
                        labels:
                                app: iot-app
                spec:
                        containers:
                                - name: nodejs
                                  image: minkuk/node
                                  ports:
                                          - containerPort: 8080
