apiVersion: v1
kind: Service
metadata:
        name: node-app
spec:
        selector:
                app: node-app
        ports:
                - protocol: "TCP"
                  port: 80
                  targetPort: 8080
                  name: http
        type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: node-app
        labels:
                app: node-app
spec:
        selector:
                matchLabels:
                        app: node-app
        replicas: 1
        template:
                metadata:
                        labels:
                                app: node-app
                spec:
                        containers:
                                - name: nodejs
                                  image: hoonyhoon/app-test:1.4
                                  ports:
                                          - containerPort: 8080
                                            name: http
