apiVersion: v1
kind: Service
metadata:
        name: iot-app
spec:
        selector:
                app: iot-app
        ports:
                - protocol: "TCP"
                  port: 80
                  targetPort: 8080
                  name: http
        type: LoadBalancer

